version: '3.8'
services:
  api-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api:
    environment: 
      - REDIS_SERVER=localhost
      - PORT=8080
    build:
      context: '.'
      dockerfile: Dockerfile
    volumes:
      - .:/app/token_events
    ports:
      - "8080:8080"
      - "5678:5678"
    depends_on:
      - api-redis
    env_file:
      - .env
    restart: always
